apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce # Один под на запись
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-path # Используйте свою StorageClass